-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-03 10:25:48 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

--Student Name: CHUKWUDI ANYANWU


-- check CONSTRAINT added : Phone number <= 10

SET ECHO ON
SPOOL prop_rental_schema_output.txt


DROP TABLE damage CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE payment CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE rent CASCADE CONSTRAINTS;

DROP TABLE tenant CASCADE CONSTRAINTS;

CREATE TABLE damage (
    dam_no                 NUMBER(7) NOT NULL,
    dam_date               DATE NOT NULL,
    dam_time               DATE NOT NULL,
    dam_type               VARCHAR2(50) NOT NULL,
    dam_cost               NUMBER(7) NOT NULL,
    prop_no                NUMBER(7) NOT NULL,
    rent_lease_startdate   DATE NOT NULL,
    pay_no                 NUMBER(7)
);

COMMENT ON COLUMN damage.dam_no IS
    'Damage identification number .... surrogate key';

COMMENT ON COLUMN damage.dam_date IS
    'damage date';

COMMENT ON COLUMN damage.dam_time IS
    'damage time';

COMMENT ON COLUMN damage.dam_type IS
    'damaage type';

COMMENT ON COLUMN damage.dam_cost IS
    'damage cost';

COMMENT ON COLUMN damage.prop_no IS
    'property number';

COMMENT ON COLUMN damage.rent_lease_startdate IS
    'start date of the lease';

COMMENT ON COLUMN damage.pay_no IS
    'payment number';

CREATE UNIQUE INDEX damage__idx ON
    damage (
        pay_no
    ASC );

ALTER TABLE damage
    ADD CONSTRAINT damage_pk PRIMARY KEY ( dam_date,
                                           dam_time,
                                           prop_no,
                                           rent_lease_startdate );

CREATE TABLE owner (
    owner_no        NUMBER(7) NOT NULL,
    owner_title     VARCHAR2(50) NOT NULL,
    owner_givname   VARCHAR2(50) NOT NULL,
    owner_famname   VARCHAR2(50) NOT NULL,
    owner_address   VARCHAR2(255) NOT NULL
);

COMMENT ON COLUMN owner.owner_no IS
    'owner no';

COMMENT ON COLUMN owner.owner_title IS
    'Owner title';

COMMENT ON COLUMN owner.owner_givname IS
    'owner given name .....first name ';

COMMENT ON COLUMN owner.owner_famname IS
    'owner family name .....last name';

COMMENT ON COLUMN owner.owner_address IS
    'Owner address ';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_no );

CREATE TABLE payment (
    pay_no                  NUMBER(7) NOT NULL,
    pay_date                DATE NOT NULL,
    pay_type                VARCHAR2(50) NOT NULL,
    pay_amount              NUMBER(7) NOT NULL,
    pay_paidby              VARCHAR2(50) NOT NULL,
    rent_lease_startdate    DATE NOT NULL,
    prop_no                 NUMBER(7) NOT NULL,
    dam_no                  NUMBER(7),
    dam_date                DATE,
    dam_time                DATE,
    prop_no1                NUMBER,
    rent_lease_startdate1   DATE
);

COMMENT ON COLUMN payment.pay_no IS
    'payment number';

COMMENT ON COLUMN payment.pay_date IS
    'payment date';

COMMENT ON COLUMN payment.pay_type IS
    'pay type';

COMMENT ON COLUMN payment.pay_amount IS
    'pay amount';

COMMENT ON COLUMN payment.pay_paidby IS
    'pay paidby';

COMMENT ON COLUMN payment.rent_lease_startdate IS
    'start date of the lease';

COMMENT ON COLUMN payment.prop_no IS
    'property number';

COMMENT ON COLUMN payment.dam_no IS
    'Damage identification number .... surrogate key';

COMMENT ON COLUMN payment.dam_date IS
    'damage date';

COMMENT ON COLUMN payment.dam_time IS
    'damage time';

COMMENT ON COLUMN payment.prop_no1 IS
    'property number';

CREATE UNIQUE INDEX payment__idx ON
    payment (
        dam_no
    ASC );

CREATE UNIQUE INDEX payment__idx ON
    payment (
        dam_date
    ASC,
        dam_time
    ASC,
        prop_no1
    ASC,
        rent_lease_startdate1
    ASC );

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( pay_no );

CREATE TABLE property (
    prop_no        NUMBER(7) NOT NULL,
    prop_address   VARCHAR2(255 CHAR) NOT NULL,
    prop_value     NUMBER(7) NOT NULL,
    owner_no       NUMBER(7) NOT NULL
);

COMMENT ON COLUMN property.prop_no IS
    'property number';

COMMENT ON COLUMN property.prop_address IS
    'property address';

COMMENT ON COLUMN property.prop_value IS
    'property value';

COMMENT ON COLUMN property.owner_no IS
    'owner no';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( prop_no );

CREATE TABLE rent (
    prop_no                NUMBER(7) NOT NULL,
    rent_lease_startdate   DATE NOT NULL,
    rent_lease_period      DATE NOT NULL,
    rent_bond              NUMBER(7) NOT NULL,
    rent_weekly_rate       NUMBER(7) NOT NULL,
    tenant_no              NUMBER(7) NOT NULL
);

COMMENT ON COLUMN rent.prop_no IS
    'property number';

COMMENT ON COLUMN rent.rent_lease_startdate IS
    'start date of the lease';

COMMENT ON COLUMN rent.rent_lease_period IS
    'duration of the lease';

COMMENT ON COLUMN rent.rent_bond IS
    'Bond paid when moving into the property ';

COMMENT ON COLUMN rent.rent_weekly_rate IS
    'weekly rent';

COMMENT ON COLUMN rent.tenant_no IS
    'Tenant identification number';

ALTER TABLE rent ADD CONSTRAINT rent_pk PRIMARY KEY ( rent_lease_startdate,
                                                      prop_no );

CREATE TABLE tenant (
    tenant_no         NUMBER(7) NOT NULL,
    tenant_fname      VARCHAR2(50) NOT NULL,
    tenant_gname      VARCHAR2(50) NOT NULL,
    tenant_address    VARCHAR2(50) NOT NULL,
    tenant_street     VARCHAR2(50) NOT NULL,
    tenant_city       VARCHAR2(15) NOT NULL,
    tenant_state      VARCHAR2(15) NOT NULL,
    tenant_postcode   CHAR(4) NOT NULL,
    tenant_phone      VARCHAR2(12) NOT NULL
);

ALTER TABLE tenant ADD CONSTRAINT chk_phone_no CHECK ( tenant_phone <= 10 );

COMMENT ON COLUMN tenant.tenant_no IS
    'Tenant identification number';

COMMENT ON COLUMN tenant.tenant_fname IS
    'Tenant first name';

COMMENT ON COLUMN tenant.tenant_gname IS
    'Tenant given name';

COMMENT ON COLUMN tenant.tenant_address IS
    'Tenant address';

COMMENT ON COLUMN tenant.tenant_street IS
    'Tenant street';

COMMENT ON COLUMN tenant.tenant_city IS
    'Tenant city';

COMMENT ON COLUMN tenant.tenant_state IS
    'Tenant state';

COMMENT ON COLUMN tenant.tenant_postcode IS
    'Tenant postcode';

COMMENT ON COLUMN tenant.tenant_phone IS
    'Tenant Phone number';

ALTER TABLE tenant ADD CONSTRAINT tenant_pk PRIMARY KEY ( tenant_no );

ALTER TABLE damage
    ADD CONSTRAINT damage_rent_relationship FOREIGN KEY ( rent_lease_startdate,
                                                          prop_no )
        REFERENCES rent ( rent_lease_startdate,
                          prop_no );

ALTER TABLE property
    ADD CONSTRAINT owner_property_relationship FOREIGN KEY ( owner_no )
        REFERENCES owner ( owner_no );

ALTER TABLE rent
    ADD CONSTRAINT property_rent_relationship FOREIGN KEY ( prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE payment
    ADD CONSTRAINT rent_payment_relationship FOREIGN KEY ( rent_lease_startdate,
                                                           prop_no )
        REFERENCES rent ( rent_lease_startdate,
                          prop_no );

ALTER TABLE rent
    ADD CONSTRAINT rent_tenant_relationship FOREIGN KEY ( tenant_no )
        REFERENCES tenant ( tenant_no );



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                             6
-- CREATE INDEX                             3
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0

--Student Name: CHUKWUDI ANYANWU
--Student Number:  30647126

SET ECHO ON
SPOOL prop_rental_schema_output.txt
