-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-17 01:48:02 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c


--Title :           ASSIGNMENT 1B 
--Student Name:     CHUKWUDI ANYANWU
--Student Number:   30647126
--Tutor :           Tianyue Ma

SET ECHO ON
SPOOL mau_schema_output.txt


DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS;

DROP TABLE artwork_status CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE exhibit CASCADE CONSTRAINTS;

DROP TABLE gallery CASCADE CONSTRAINTS;

DROP TABLE sale CASCADE CONSTRAINTS;

DROP TABLE style CASCADE CONSTRAINTS;

CREATE TABLE artist (
    artist_code             NUMBER(7) NOT NULL,
    artist_fname            VARCHAR2(25) NOT NULL,
    artist_lname            VARCHAR2(25) NOT NULL,
    artist_street           VARCHAR2(40) NOT NULL,
    artist_town             VARCHAR2(20) NOT NULL,
    artist_state            VARCHAR2(3) NOT NULL,
    artist_phone            VARCHAR2(10),
    artist_post_code        CHAR(4) NOT NULL,
    artist_stock_quantity   NUMBER(4) NOT NULL
);

COMMENT ON COLUMN artist.artist_code IS
    'Artist identification number';

COMMENT ON COLUMN artist.artist_fname IS
    'Artist first name';

COMMENT ON COLUMN artist.artist_lname IS
    'Artist Last name';

COMMENT ON COLUMN artist.artist_street IS
    'Artist street ';

COMMENT ON COLUMN artist.artist_town IS
    'Artist Town';

COMMENT ON COLUMN artist.artist_state IS
    'Artist State......All artist are from australia';

COMMENT ON COLUMN artist.artist_phone IS
    'Artist mobile number
Not all Artist register with their phone numbers ';

COMMENT ON COLUMN artist.artist_post_code IS
    'Artist post code.
This must be 4 digits only.';

COMMENT ON COLUMN artist.artist_stock_quantity IS
    'Artist artwork stock quantity ';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE artwork (
    artwork_id                       NUMBER(7) NOT NULL,
    artwork_no                       NUMBER(4) NOT NULL,
    artist_code                      NUMBER(7) NOT NULL,
    artwork_title                    VARCHAR2(50) NOT NULL,
    artwork_date_added_tostock       DATE NOT NULL,
    artwork_artist_min_price         NUMBER(7) NOT NULL,
    artwork_media_description_link   VARCHAR2(250) NOT NULL,
    child_style                      VARCHAR2(25) NOT NULL
);

COMMENT ON COLUMN artwork.artwork_id IS
    'Surrogate key that uniquely identify artwork.';

COMMENT ON COLUMN artwork.artwork_no IS
    'Artist Artwork Number';

COMMENT ON COLUMN artwork.artist_code IS
    'Artist identification number';

COMMENT ON COLUMN artwork.artwork_title IS
    'artwork title ';

COMMENT ON COLUMN artwork.artwork_date_added_tostock IS
    'Date Artwork was added to stock';

COMMENT ON COLUMN artwork.artwork_artist_min_price IS
    'Artist prefered minimium price';

COMMENT ON COLUMN artwork.artwork_media_description_link IS
    'Artwork Media Description Link ';

COMMENT ON COLUMN artwork.child_style IS
    'child style ... child style can also be the parent style';

CREATE UNIQUE INDEX artwork__idx ON
    artwork (
        child_style
    ASC );

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( artwork_id );

ALTER TABLE artwork
    ADD CONSTRAINT nk_artwork UNIQUE ( artwork_no,
                                       artist_code,
                                       artwork_media_description_link );

CREATE TABLE artwork_status (
    artwork_status_date   DATE NOT NULL,
    artwork_no            NUMBER(7) NOT NULL,
    artist_code           NUMBER(7) NOT NULL,
    artwork_status        VARCHAR2(30) NOT NULL,
    artwork_id            NUMBER NOT NULL,
    gallery_id            NUMBER(4),
    artwork_id1           NUMBER(7) NOT NULL
);

ALTER TABLE artwork_status
    ADD CONSTRAINT chk_artwork_status CHECK ( artwork_status IN (
        'On display by a gallery',
        'Returned to Artist',
        'Sold',
        'in MAU storage at the MAU central warehouse',
        'in transit (being shipped to/from a gallery)'
    ) );

COMMENT ON COLUMN artwork_status.artwork_status_date IS
    'Artwork Status Date ';

COMMENT ON COLUMN artwork_status.artwork_no IS
    'Artist Artwork Number';

COMMENT ON COLUMN artwork_status.artist_code IS
    'Artist identification number';

COMMENT ON COLUMN artwork_status.artwork_status IS
    'Status of the artwork 

Artwork status must be one of the following: 
? in MAU storage at the MAU central warehouse
? in transit (being shipped to/from a gallery)
? on display by a gallery
? sold
? returned to the artist'
    ;

COMMENT ON COLUMN artwork_status.artwork_id IS
    'Surrogate key that uniquely identify artwork.';

COMMENT ON COLUMN artwork_status.gallery_id IS
    'Gallery Identification Number';

COMMENT ON COLUMN artwork_status.artwork_id1 IS
    'Surrogate key that uniquely identify artwork.';

ALTER TABLE artwork_status ADD CONSTRAINT artwork_status_pk PRIMARY KEY ( artwork_status_date,
                                                                          artwork_id1 );

CREATE TABLE customer (
    customer_id              NUMBER(7) NOT NULL,
    customer_fname           VARCHAR2(25) NOT NULL,
    customer_lname           VARCHAR2(25) NOT NULL,
    customer_street          VARCHAR2(40) NOT NULL,
    customer_town            VARCHAR2(20) NOT NULL,
    customer_state           VARCHAR2(3) NOT NULL,
    customer_postcode        CHAR(4) NOT NULL,
    customer_business_name   VARCHAR2(25)
);

COMMENT ON COLUMN customer.customer_id IS
    'Customer Identification';

COMMENT ON COLUMN customer.customer_fname IS
    'Customer First name';

COMMENT ON COLUMN customer.customer_lname IS
    'Customer Last name';

COMMENT ON COLUMN customer.customer_street IS
    'Customer street name.
Assumption: All customers are from Australia.';

COMMENT ON COLUMN customer.customer_town IS
    'Customer Town Name';

COMMENT ON COLUMN customer.customer_state IS
    'Customer State Abbreviation ';

COMMENT ON COLUMN customer.customer_postcode IS
    'Customer Post Code';

COMMENT ON COLUMN customer.customer_business_name IS
    'Customer Business Name';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE exhibit (
    exhibit_id           NUMBER(7) NOT NULL,
    exhibit_start_date   DATE NOT NULL,
    exhibit_end_date     DATE NOT NULL,
    artwork_in_catalog   CHAR(3) NOT NULL,
    artwork_id           NUMBER(7) NOT NULL,
    gallery_id           NUMBER(4) NOT NULL
);

ALTER TABLE exhibit
    ADD CONSTRAINT chk_artwork_catalog CHECK ( artwork_in_catalog IN (
        'No',
        'Yes'
    ) );

COMMENT ON COLUMN exhibit.exhibit_id IS
    'Surrogate Key to uniquely identify each display at the exhibit';

COMMENT ON COLUMN exhibit.exhibit_start_date IS
    'Exhibit Start Date';

COMMENT ON COLUMN exhibit.exhibit_end_date IS
    'Exhibit end date ';

COMMENT ON COLUMN exhibit.artwork_in_catalog IS
    'Is the artwork exhibited featured in catalog?! ';

COMMENT ON COLUMN exhibit.artwork_id IS
    'Surrogate key that uniquely identify artwork.';

COMMENT ON COLUMN exhibit.gallery_id IS
    'Gallery Identification Number';

ALTER TABLE exhibit ADD CONSTRAINT exhibit_pk PRIMARY KEY ( exhibit_id );

ALTER TABLE exhibit
    ADD CONSTRAINT nk_exhibit UNIQUE ( gallery_id,
                                       artwork_id,
                                       exhibit_start_date );

CREATE TABLE gallery (
    gallery_id                NUMBER(4) NOT NULL,
    gallery_name              VARCHAR2(50) NOT NULL,
    gallery_mfname            VARCHAR2(25) NOT NULL,
    gallery_street            VARCHAR2(40) NOT NULL,
    gallery_town              VARCHAR2(15) NOT NULL,
    gallery_state             VARCHAR2(3) NOT NULL,
    gallery_opens_time        DATE NOT NULL,
    gallery_closes_time       DATE NOT NULL,
    gallery_contact_no        VARCHAR2(10) NOT NULL,
    gallery_sale_percentage   NUMBER(2) NOT NULL,
    gallery_mlname            VARCHAR2(25) NOT NULL,
    gallery_postcode          CHAR(4) NOT NULL
);

COMMENT ON COLUMN gallery.gallery_id IS
    'Gallery Identification Number';

COMMENT ON COLUMN gallery.gallery_name IS
    'Gallery Name';

COMMENT ON COLUMN gallery.gallery_mfname IS
    'Gallery Manager first Name';

COMMENT ON COLUMN gallery.gallery_street IS
    'Gallery Street Name';

COMMENT ON COLUMN gallery.gallery_town IS
    'Gallery Town ';

COMMENT ON COLUMN gallery.gallery_state IS
    'Gallery State';

COMMENT ON COLUMN gallery.gallery_opens_time IS
    'Gallery Opening Time';

COMMENT ON COLUMN gallery.gallery_closes_time IS
    'Gallery Closing Time';

COMMENT ON COLUMN gallery.gallery_contact_no IS
    'Gallery Phone Number';

COMMENT ON COLUMN gallery.gallery_sale_percentage IS
    'Gallery sale percentage';

COMMENT ON COLUMN gallery.gallery_mlname IS
    'gallery manager last name';

COMMENT ON COLUMN gallery.gallery_postcode IS
    'Gallery post code';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gallery_id );

CREATE TABLE sale (
    sale_id       NUMBER(7) NOT NULL,
    sale_date     DATE NOT NULL,
    sale_price    NUMBER(7) NOT NULL,
    customer_id   NUMBER(7) NOT NULL,
    exhibit_id    NUMBER(7) NOT NULL
);

COMMENT ON COLUMN sale.sale_id IS
    'Sale Identification Number';

COMMENT ON COLUMN sale.sale_date IS
    'Sale Date';

COMMENT ON COLUMN sale.sale_price IS
    'Sale Price';

COMMENT ON COLUMN sale.customer_id IS
    'Customer Identification';

COMMENT ON COLUMN sale.exhibit_id IS
    'Surrogate Key to uniquely identify each display at the exhibit';

CREATE UNIQUE INDEX sale__idx ON
    sale (
        exhibit_id
    ASC );

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

CREATE TABLE style (
    child_style    VARCHAR2(25) NOT NULL,
    parent_style   VARCHAR2(25) NOT NULL
);

COMMENT ON COLUMN style.child_style IS
    'child style ... child style can also be the parent style';

COMMENT ON COLUMN style.parent_style IS
    'child style ... child style can also be the parent style';

ALTER TABLE style ADD CONSTRAINT style_pk PRIMARY KEY ( child_style );

ALTER TABLE artwork
    ADD CONSTRAINT artist_artwork_connection FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE exhibit
    ADD CONSTRAINT artwork_exhibit_connect FOREIGN KEY ( artwork_id )
        REFERENCES artwork ( artwork_id );

ALTER TABLE artwork_status
    ADD CONSTRAINT artwork_status_connection FOREIGN KEY ( artwork_id1 )
        REFERENCES artwork ( artwork_id );

ALTER TABLE artwork_status
    ADD CONSTRAINT artwork_status_gallery_connect FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE artwork
    ADD CONSTRAINT artwork_style_connect FOREIGN KEY ( child_style )
        REFERENCES style ( child_style );

ALTER TABLE sale
    ADD CONSTRAINT exhibit_sale_connect FOREIGN KEY ( exhibit_id )
        REFERENCES exhibit ( exhibit_id );

ALTER TABLE exhibit
    ADD CONSTRAINT gallery_exhibit_connection FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE style
    ADD CONSTRAINT parent_style_connect FOREIGN KEY ( parent_style )
        REFERENCES style ( child_style );

ALTER TABLE sale
    ADD CONSTRAINT sale_customer_connect FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             2
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0



SPOOL OFF
SET ECHO OFF
